version: "3.8"

services:
  {{#if hdpAdapter}}
  {{> hdp-adapter }}
  {{/if}}

  {{#if CommServerAdapter}}
  {{> comm-server-adapter }}
  {{/if}}

  {{#if medtronicDbsApi}}
  {{> medtronic-dbs-api }}
  {{/if}}

networks:
  proxy:
    external: true
