HOSTNAME: {{HOSTNAME}}

AUTH_CLIENT_SECRET: {{AUTH_CLIENT_SECRET}}
SIGNING_SECRET: {{SIGNING_SECRET}}

KEYCLOAK_USER: {{KEYCLOAK_USER}}
KEYCLOAK_PASSWORD: {{KEYCLOAK_PASSWORD}}

KEYCLOAK_DB_USER: {{KEYCLOAK_DB_USER}}
KEYCLOAK_DB_PASSWORD: {{KEYCLOAK_DB_PASSWORD}}

FHIR_DB_USER: {{FHIR_DB_USER}}
FHIR_DB_PASSWORD: {{FHIR_DB_PASSWORD}}

SENTRY_ENVIRONMENT: {{SENTRY_ENVIRONMENT}}
FHIR_SERVER_SENTRY_DSN: {{FHIR_SERVER_SENTRY_DSN}}
FILE_STORAGE_API_SENTRY_DSN: {{FILE_STORAGE_API_SENTRY_DSN}}
ICD_10_API_SENTRY_DSN: {{ICD_10_API_SENTRY_DSN}}
