error-handler:
  image: ghcr.io/dot-base/error-handler:next
  networks:
    - proxy
  deploy:
    replicas: 1
    update_config:
      parallelism: 2
      delay: 60s
    restart_policy:
      condition: on-failure
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.error-router.priority=1"
      - "traefik.http.routers.error-router.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-router.middlewares=error-pages-middleware"

      - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
      - "traefik.http.middlewares.error-pages-middleware.errors.service=error-handler"
      - "traefik.http.middlewares.error-pages-middleware.errors.query=/{status}/index.html"

      - "traefik.http.routers.error-static.tls=true"
      - "traefik.http.routers.error-static.rule=Host(`error.${HOSTNAME}`)"

      - "traefik.http.services.error-handler.loadbalancer.server.port=80"
