keycloak:
  image: jboss/keycloak:11.0.3
  networks:
    - proxy
    - keycloak
  environment:
    - DB_VENDOR=postgres
    - DB_ADDR=keycloak-db
    - DB_USER=${KEYCLOAK_DB_USER}
    - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    - KEYCLOAK_USER=${KEYCLOAK_USER}
    - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    - KEYCLOAK_IMPORT=/tmp/dotbase-realm.json
    - PROXY_ADRESS_FORWARDING=true
  volumes:
    - ./config/dotbase-realm.json:/tmp/dotbase-realm.json
  deploy:
    replicas: 1
    update_config:
      parallelism: 2
      delay: 60s
    restart_policy:
      condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.keycloak.rule=Host(`sso.${HOSTNAME}`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

keycloak-db:
  image: postgres:13-alpine
  networks:
    - keycloak
  volumes:
    - keycloak-data:/var/lib/postgresql/data
  environment:
    - POSTGRES_DB=keycloak
    - POSTGRES_USER=${KEYCLOAK_DB_USER}
    - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
  deploy:
    placement:
      max_replicas_per_node: 1
